package com.sway3i.entities.enums;

public enum AuthorityEnum {

    GRANT_AUTHORITY_TO_ROLE,
    REVOKE_AUTHORITY_FROM_ROLE,
    ASSIGN_ROLE_TO_USER,
    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,
    VIEW_ROLES,
    UPDATE_USERS,
    VIEW_USERS,
    DELETE_USERS,
    VIEW_AUTHORITIES,


    VIEW_COURSES,
    VIEW_ONE_COURSE,
    CREATE_COURSE,
    UPDATE_COURSE,
    DELETE_COURSE,


}