# Server Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

# Spring Configuration
spring:

  #to enable colors when you run your app outside intellij
  output:
    ansi:
      enabled: always

  # Database Configuration
  datasource:
    url: jdbc:mysql://mysql:3306/sway3i-v3?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
  liquibase:
    enabled: true
    change-log: db/master.xml
